In [1]:
import numpy as np


In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [3, 4, 5]])
print(arr1)
print('###')
print(arr2)

[1 2 3]
###
[[1 2 3]
 [3 4 5]]


In [11]:
a = np.array([1, 1.223])
print(a)

[1.    1.223]


In [18]:
iden = np.eye(3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
one = np.ones((2, 3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
zero = np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
xplot = np.arange(0, 10, 3)
xplot

array([0, 3, 6, 9])

In [27]:
arr2.shape

(2, 3)

In [29]:
arr2.size

6

In [28]:
arr2.reshape(3,2)

array([[1, 2],
       [3, 3],
       [4, 5]])

In [33]:
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [34]:
arr2.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [38]:
arr2[]

array([[1, 2, 3],
       [3, 4, 5]])

In [39]:
arr2 * 3

array([[ 3,  6,  9],
       [ 9, 12, 15]])

In [40]:
arr2 + 3

array([[4, 5, 6],
       [6, 7, 8]])

In [41]:
np.exp(arr2)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [42]:
np.sin(arr2)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [ 0.14112001, -0.7568025 , -0.95892427]])

In [43]:
np.sum(arr2)

18

In [59]:
np.sum(arr2, axis=1)

array([ 6, 12])

In [67]:
np.sum(arr2, axis=0)

array([4, 6, 8])

In [60]:
a = np.array([[[1,2,3,5], [1,2,3,2]], [[1,2,3,1],[5,6,1,2]]])
a

array([[[1, 2, 3, 5],
        [1, 2, 3, 2]],

       [[1, 2, 3, 1],
        [5, 6, 1, 2]]])

In [61]:
a.shape

(2, 2, 4)

In [63]:
np.sum(a, axis=0)

array([[2, 4, 6, 6],
       [6, 8, 4, 4]])

In [64]:
np.sum(a, axis=1)

array([[2, 4, 6, 7],
       [6, 8, 4, 3]])

In [65]:
np.sum(a, axis=2)

array([[11,  8],
       [ 7, 14]])

In [66]:
# np.sum(a, axis=3)

In [76]:
arr3 = np.ones(arr2.shape)
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [77]:
arr3*arr2

array([[1., 2., 3.],
       [3., 4., 5.]])

In [80]:
arr4 = np.ones(arr2.T.shape)
arr4

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [83]:
arr4.dot(arr2)
# np.dot(arr4, arr2)

array([[4., 6., 8.],
       [4., 6., 8.],
       [4., 6., 8.]])

In [84]:
arr1

array([1, 2, 3])

In [85]:
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [86]:
arr1 + arr2

array([[2, 4, 6],
       [4, 6, 8]])

In [87]:
arr1 * arr2

array([[ 1,  4,  9],
       [ 3,  8, 15]])

In [99]:
arr3 = np.array([[1], [2]])
arr3

array([[1],
       [2]])

In [100]:
arr3 * arr2

array([[ 1,  2,  3],
       [ 6,  8, 10]])

In [101]:
arr3 + arr2

array([[2, 3, 4],
       [5, 6, 7]])

In [96]:
arr4 = np.array([1, 2])
arr4.shape

(2,)

In [98]:
arr2 + arr4

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 